<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Cataben.Worker-61cc0b92-a30c-4876-b8f3-c9842df23ed5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cataben.Application\Cataben.Application.csproj" />
    <ProjectReference Include="..\Cataben.Domain\Cataben.Domain.csproj" />
  </ItemGroup>
</Project>
